"""empty message

Revision ID: ea6f1614086b
Revises: 
Create Date: 2019-12-24 17:02:11.248926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ea6f1614086b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('currency_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency_code', sa.String(length=5), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('currency_code')
    )
    op.create_table('employee_model',
    sa.Column('uuid', sa.String(length=200), nullable=False),
    sa.Column('first_name', sa.String(length=200), nullable=True),
    sa.Column('last_name', sa.String(length=200), nullable=True),
    sa.PrimaryKeyConstraint('uuid')
    )
    op.create_table('transaction_model',
    sa.Column('uuid', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.String(length=200), nullable=True),
    sa.Column('currency_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('employee_id', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('approval_status', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['currency_id'], ['currency_model.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employee_model.uuid'], ),
    sa.PrimaryKeyConstraint('uuid'),
    sa.UniqueConstraint('uuid')
    )
    op.create_index(op.f('ix_transaction_model_amount'), 'transaction_model', ['amount'], unique=False)
    op.create_index(op.f('ix_transaction_model_description'), 'transaction_model', ['description'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transaction_model_description'), table_name='transaction_model')
    op.drop_index(op.f('ix_transaction_model_amount'), table_name='transaction_model')
    op.drop_table('transaction_model')
    op.drop_table('employee_model')
    op.drop_table('currency_model')
    # ### end Alembic commands ###
